version: '3.8'

services:
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: ci3-php
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - ci-network

  mysql:
    image: mysql:8.0.3
    container_name: ci3-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ci_db
      MYSQL_USER: ci_user
      MYSQL_PASSWORD: ci_pass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - ci-network
    platform: linux/amd64

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ci3-dashboard-pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass
    depends_on:
      - mysql
    networks:
      - ci-network
    platform: linux/amd64

volumes:
  dbdata:

networks:
  ci-network:
